import org.apache.shiro.grails.AccessControlBuilder;
import grails.util.Environment;

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class ShiroSecurityFilters {
    def filters = {
		auth(controller:'*', action:'*') {
			before = {
				if (!controllerName || controllerName == 'assets') return true
				def isProd = (Environment.current == Environment.PRODUCTION)
				if (isProd && !request.getRequestURL().contains("befitmcz.sslblindado.com")) {
					def url = "https://befitmcz.sslblindado.com" + request.forwardURI
					redirect(url: url)
					return false
				}
				accessControl {
					role("administrador")
				}
			}
		}
    }
}
