/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class ShiroSecurityFilters {
    def filters = {
		auth(controller:'*', action:'*') {
			before = {
				if (!controllerName || controllerName == 'assets') return true
				accessControl {
					role("administrador")
				}
			}
		}
    }
}
